POST http://localhost:3001/api/discs
content-type: application/json

{
    "name": "New disc",
    "manufacturer": "Dynamic Discs",
    "type": "putter",
    "speed": 1,
    "glide": 4,
    "turn": 0,
    "fade": 0
}
